###
GET http://localhost:5000/ToDos

###
POST http://localhost:5000/ToDos/Create
Content-Type: application/json

{
    "content": "Understand L"
}
###
POST http://localhost:5000/ToDos/Delete
Content-Type: application/json

{
    "toDoId": "65b5edd6bd244a5e32a43e2f"
}
###
POST http://localhost:5000/ToDos/Update
Content-Type: application/json

{
    "toDoId": "65b5e6546df81154e1363fe1",
    "updateKey": "completed",
    "updateValue": true
}
###
POST http://localhost:5000/ToDos/Update
Content-Type: application/json

{
    "toDoId": "65b5edd6bd244a5e32a43e2f",
    "updateKey": "content",
    "updateValue": "Understand H edit-2"
}